"""Low-level tile effects and valid-moves pool management.

All functions mutate the GameState directly. No validation; callers (rules.py
and minimax.py) are responsible for ensuring moves are legal before calling
apply_move().
"""

from game.board import (
    MOUNTAIN, FOREST, PLAINS, TOWER, CAVE, WIZARD, BARBARIAN, DOMAIN, CLAIMABLE
)

CARDINALS = [(-1, 0), (1, 0), (0, -1), (0, 1)]


# ---------------------------------------------------------------------------
# Valid-move pool helpers
# ---------------------------------------------------------------------------

def _add_valid_move(state, r, c, player, cave_source=None):
    """Add (r, c) to player's valid moves.

    cave_source: (sr, sc) of the cave that generated this move, or None for
                 all non-cave sources.
    Does nothing if the tile is unclaimable or already owned.
    """
    tile = state.board[r][c]
    if tile["type"] in (MOUNTAIN, BARBARIAN) or tile["owner"] is not None:
        return

    if (r, c) not in state.valid_moves[player]:
        state.valid_moves[player][(r, c)] = {"non_cave": False, "cave_sources": []}

    entry = state.valid_moves[player][(r, c)]
    if cave_source is not None:
        if cave_source not in entry["cave_sources"]:
            entry["cave_sources"].append(cave_source)
    else:
        entry["non_cave"] = True

    tile["visible"] = True


def add_tile_valid_moves(state, r, c, player):
    """Contribute the valid moves generated by the already-claimed tile at (r, c)."""
    tile = state.board[r][c]
    t = tile["type"]

    if t in (FOREST, DOMAIN):
        _forest_moves(state, r, c, player)
    elif t == PLAINS:
        _plains_moves(state, r, c, player)
    elif t == TOWER:
        _tower_moves(state, r, c, player)
    elif t == CAVE and not tile["inert"]:
        _cave_moves(state, r, c, player)
    # WIZARD / BARBARIAN / MOUNTAIN: no valid moves added


def _forest_moves(state, r, c, player):
    for dr, dc in CARDINALS:
        nr, nc = r + dr, c + dc
        if state.in_bounds(nr, nc):
            _add_valid_move(state, nr, nc, player)


def _plains_moves(state, r, c, player):
    """Tiles at manhattan distance ≤ 2 become valid moves; same area revealed."""
    _reveal_area(state, r, c, 2)
    for nr in range(state.height):
        for nc in range(state.width):
            if abs(nr - r) + abs(nc - c) <= 2:
                _add_valid_move(state, nr, nc, player)


def _tower_moves(state, r, c, player):
    """Tiles at exactly manhattan distance 3 become valid moves; distance ≤ 3 revealed."""
    _reveal_area(state, r, c, 3)
    for nr in range(state.height):
        for nc in range(state.width):
            if abs(nr - r) + abs(nc - c) == 3:
                _add_valid_move(state, nr, nc, player)


def _cave_moves(state, r, c, player):
    """Add all other unclaimed non-inert Cave tiles as valid moves via cave link."""
    for nr in range(state.height):
        for nc in range(state.width):
            if (nr, nc) == (r, c):
                continue
            tile = state.board[nr][nc]
            if tile["type"] == CAVE and not tile["inert"] and tile["owner"] is None:
                _add_valid_move(state, nr, nc, player, cave_source=(r, c))
    for dr, dc in CARDINALS:
        nr, nc = r + dr, c + dc
        if state.in_bounds(nr, nc):
            _add_valid_move(state, nr, nc, player)


# ---------------------------------------------------------------------------
# Fog reveal
# ---------------------------------------------------------------------------

def _reveal_area(state, r, c, radius):
    """Set visible=True for all tiles within manhattan distance radius."""
    for nr in range(state.height):
        for nc in range(state.width):
            if abs(nr - r) + abs(nc - c) <= radius:
                state.board[nr][nc]["visible"] = True


def _reveal_neighbors(state, r, c):
    """Reveal all cardinally adjacent tiles. Applied on every claim as the minimum reveal."""
    for dr, dc in CARDINALS:
        nr, nc = r + dr, c + dc
        if state.in_bounds(nr, nc):
            state.board[nr][nc]["visible"] = True


# ---------------------------------------------------------------------------
# Main move application
# ---------------------------------------------------------------------------

def apply_move(state, r, c, player, wizard=False):
    """Claim the tile at (r, c) for player.

    wizard=True: this is a wizard-ability teleport move (not a normal move).

    Returns a list of event dicts describing what happened.
    """
    events = []
    tile = state.board[r][c]

    if wizard:
        # Wizard teleport: claim any unclaimed non-mountain tile
        state.wizard_used[player] = True
        tile["owner"] = player
        tile["visible"] = True
        state.scores[player] += 1
        _remove_from_pools(state, r, c)
        _reveal_neighbors(state, r, c)
        add_tile_valid_moves(state, r, c, player)
        events.append({"type": "wizard_used", "player": player, "position": [r, c]})
    else:
        entry = state.valid_moves[player].get((r, c), {"non_cave": True, "cave_sources": []})
        is_cave_link = (
            tile["type"] == CAVE
            and not entry["non_cave"]
            and len(entry["cave_sources"]) > 0
        )

        if is_cave_link:
            source = entry["cave_sources"][0]
            # Claim and inert both caves
            tile["owner"] = player
            tile["inert"] = True
            tile["visible"] = True
            state.board[source[0]][source[1]]["inert"] = True
            state.scores[player] += 1  # source cave was already counted

            _remove_from_pools(state, r, c)
            _drop_cave_source_moves(state, source)
            _reveal_neighbors(state, r, c)
            events.append({
                "type": "cave_connection",
                "cave1": list(source),
                "cave2": [r, c],
            })
        else:
            # Normal claim
            tile["owner"] = player
            tile["visible"] = True
            state.scores[player] += 1
            _remove_from_pools(state, r, c)
            _reveal_neighbors(state, r, c)

            if tile["type"] == WIZARD:
                state.wizard_held_by = player
                events.append({"type": "wizard_acquired", "player": player})
            else:
                add_tile_valid_moves(state, r, c, player)

    # Trigger any newly visible barbarians
    events.extend(_process_barbarian_triggers(state))
    return events


# ---------------------------------------------------------------------------
# Pool mutation helpers
# ---------------------------------------------------------------------------

def _remove_from_pools(state, r, c):
    """Remove (r, c) from both players' valid-move pools."""
    for player in ("human", "ai"):
        state.valid_moves[player].pop((r, c), None)


def _drop_cave_source_moves(state, cave_pos):
    """After cave_pos becomes inert, remove any valid-move entries that relied
    solely on cave_pos as their source.  Also scrub cave_pos from other entries.
    """
    for player in ("human", "ai"):
        to_remove = []
        for (r, c), entry in state.valid_moves[player].items():
            if cave_pos in entry["cave_sources"]:
                entry["cave_sources"].remove(cave_pos)
                if not entry["cave_sources"] and not entry["non_cave"]:
                    to_remove.append((r, c))
        for pos in to_remove:
            state.valid_moves[player].pop(pos, None)


# ---------------------------------------------------------------------------
# Barbarian handling
# ---------------------------------------------------------------------------

def _process_barbarian_triggers(state):
    """Trigger all currently visible barbarian tiles.

    Uses a restart-loop so that if multiple barbarians were already visible
    before this move they all fire, but a barbarian's charge cannot newly
    reveal (and therefore trigger) a previously hidden barbarian.
    """
    events = []
    triggered = set()

    while True:
        found = None
        for r in range(state.height):
            for c in range(state.width):
                if (r, c) not in triggered:
                    tile = state.board[r][c]
                    if tile["type"] == BARBARIAN and tile["visible"]:
                        found = (r, c)
                        break
            if found:
                break
        if found is None:
            break
        triggered.add(found)
        events.append(_trigger_barbarian(state, found[0], found[1]))

    return events


def _barbarian_direction(state, r, c):
    """Return the direction that gives the longest path from (r, c) to a board edge.

    Candidates and their path lengths (number of tiles from position to edge):
      left  → c
      right → width  - 1 - c
      up    → r
      down  → height - 1 - r

    Ties broken in priority order: left > right > up > down.
    """
    options = [
        ("left",  c),
        ("right", state.width  - 1 - c),
        ("up",    r),
        ("down",  state.height - 1 - r),
    ]
    return max(options, key=lambda x: x[1])[0]


def _trigger_barbarian(state, r, c):
    """Charge the barbarian at (r, c) in the chosen direction to the board edge.

    - Picks the direction with the longest remaining path from the barbarian.
    - Charges from the barbarian's tile to the edge in that direction.
    - Only unclaims already-owned tiles; does NOT reveal any hidden tiles.
    - The barbarian tile itself converts to claimable Forest afterwards.
    """
    direction = _barbarian_direction(state, r, c)

    if direction == "left":
        for nc in range(0, c + 1):
            _barbarian_hit(state, r, nc)
    elif direction == "right":
        for nc in range(c, state.width):
            _barbarian_hit(state, r, nc)
    elif direction == "up":
        for nr in range(0, r + 1):
            _barbarian_hit(state, nr, c)
    else:  # down
        for nr in range(r, state.height):
            _barbarian_hit(state, nr, c)

    # Barbarian tile converts to claimable Forest
    state.board[r][c]["type"] = FOREST
    state.board[r][c]["visible"] = True

    # Recompute valid moves since owned tiles may have been unclaimed
    recompute_valid_moves(state)

    return {"type": "barbarian_triggered", "position": [r, c], "direction": direction}


def _barbarian_hit(state, r, c):
    """Barbarian charges through tile at (r, c): unclaims it if owned.

    Does NOT reveal hidden tiles. Mountains are passed through untouched.
    """
    tile = state.board[r][c]
    if tile["type"] == MOUNTAIN:
        return
    if tile["owner"] is not None:
        state.scores[tile["owner"]] -= 1
        tile["owner"] = None


# ---------------------------------------------------------------------------
# Full valid-moves recomputation (used after barbarian charges)
# ---------------------------------------------------------------------------

def recompute_valid_moves(state):
    """Rebuild both players' valid-move pools from scratch based on owned tiles.

    Tower and Plains fog reveals are already encoded in tile["visible"] so
    re-applying their move-generation only adds valid moves without re-triggering
    reveals.
    """
    state.valid_moves = {"human": {}, "ai": {}}
    for r in range(state.height):
        for c in range(state.width):
            tile = state.board[r][c]
            if tile["owner"] in ("human", "ai"):
                add_tile_valid_moves(state, r, c, tile["owner"])
